package OrderApp.OrderPackage;


/**
* OrderApp/OrderPackage/CurrentOrdersHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Order.idl
* Wednesday, March 15, 2023 1:04:58 AM CDT
*/

abstract public class CurrentOrdersHelper
{
  private static String  _id = "IDL:OrderApp/Order/CurrentOrders:1.0";

  public static void insert (org.omg.CORBA.Any a, OrderApp.OrderPackage.OrderEntry[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static OrderApp.OrderPackage.OrderEntry[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = OrderApp.OrderPackage.OrderEntryHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (OrderApp.OrderPackage.CurrentOrdersHelper.id (), "CurrentOrders", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static OrderApp.OrderPackage.OrderEntry[] read (org.omg.CORBA.portable.InputStream istream)
  {
    OrderApp.OrderPackage.OrderEntry value[] = null;
    int _len0 = istream.read_long ();
    value = new OrderApp.OrderPackage.OrderEntry[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = OrderApp.OrderPackage.OrderEntryHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, OrderApp.OrderPackage.OrderEntry[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      OrderApp.OrderPackage.OrderEntryHelper.write (ostream, value[_i0]);
  }

}
