package OrderApp.OrderPackage;


/**
* OrderApp/OrderPackage/MenuHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Order.idl
* Wednesday, March 15, 2023 12:27:39 AM CDT
*/

abstract public class MenuHelper
{
  private static String  _id = "IDL:OrderApp/Order/Menu:1.0";

  public static void insert (org.omg.CORBA.Any a, OrderApp.OrderPackage.Menu that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static OrderApp.OrderPackage.Menu extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[0] = new org.omg.CORBA.StructMember (
            "friedChickenPrice",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[1] = new org.omg.CORBA.StructMember (
            "colaPrice",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (OrderApp.OrderPackage.MenuHelper.id (), "Menu", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static OrderApp.OrderPackage.Menu read (org.omg.CORBA.portable.InputStream istream)
  {
    OrderApp.OrderPackage.Menu value = new OrderApp.OrderPackage.Menu ();
    value.friedChickenPrice = istream.read_short ();
    value.colaPrice = istream.read_short ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, OrderApp.OrderPackage.Menu value)
  {
    ostream.write_short (value.friedChickenPrice);
    ostream.write_short (value.colaPrice);
  }

}
