package OrderApp.OrderPackage;


/**
* OrderApp/OrderPackage/Menu.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Order.idl
* Wednesday, March 15, 2023 12:27:39 AM CDT
*/

public final class Menu implements org.omg.CORBA.portable.IDLEntity
{
  public short friedChickenPrice = (short)0;
  public short colaPrice = (short)0;

  public Menu ()
  {
  } // ctor

  public Menu (short _friedChickenPrice, short _colaPrice)
  {
    friedChickenPrice = _friedChickenPrice;
    colaPrice = _colaPrice;
  } // ctor

} // class Menu
