package OrderApp.OrderPackage;

/**
* OrderApp/OrderPackage/OrderEntryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Order.idl
* Wednesday, March 15, 2023 1:04:58 AM CDT
*/

public final class OrderEntryHolder implements org.omg.CORBA.portable.Streamable
{
  public OrderApp.OrderPackage.OrderEntry value = null;

  public OrderEntryHolder ()
  {
  }

  public OrderEntryHolder (OrderApp.OrderPackage.OrderEntry initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = OrderApp.OrderPackage.OrderEntryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    OrderApp.OrderPackage.OrderEntryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return OrderApp.OrderPackage.OrderEntryHelper.type ();
  }

}
