package OrderApp.OrderPackage;


/**
* OrderApp/OrderPackage/OrderEntry.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Order.idl
* Wednesday, March 15, 2023 1:04:58 AM CDT
*/

public final class OrderEntry implements org.omg.CORBA.portable.IDLEntity
{
  public String userName = null;
  public OrderApp.OrderPackage.OrderStatus value = null;

  public OrderEntry ()
  {
  } // ctor

  public OrderEntry (String _userName, OrderApp.OrderPackage.OrderStatus _value)
  {
    userName = _userName;
    value = _value;
  } // ctor

} // class OrderEntry
