package OrderApp.OrderPackage;

/**
* OrderApp/OrderPackage/OrderStatusHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Order.idl
* Wednesday, March 15, 2023 1:04:58 AM CDT
*/

public final class OrderStatusHolder implements org.omg.CORBA.portable.Streamable
{
  public OrderApp.OrderPackage.OrderStatus value = null;

  public OrderStatusHolder ()
  {
  }

  public OrderStatusHolder (OrderApp.OrderPackage.OrderStatus initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = OrderApp.OrderPackage.OrderStatusHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    OrderApp.OrderPackage.OrderStatusHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return OrderApp.OrderPackage.OrderStatusHelper.type ();
  }

}
