package OrderApp;


/**
* OrderApp/OrderPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Order.idl
* Thursday, March 16, 2023 1:07:44 AM CDT
*/

public abstract class OrderPOA extends org.omg.PortableServer.Servant
 implements OrderApp.OrderOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("view_menu", new java.lang.Integer (0));
    _methods.put ("place_order", new java.lang.Integer (1));
    _methods.put ("check_order_status", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // OrderApp/Order/view_menu
       {
         String $result = null;
         $result = this.view_menu ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // OrderApp/Order/place_order
       {
         String usrName = in.read_string ();
         short friedChickenQuant = in.read_short ();
         short colaQuant = in.read_short ();
         String $result = null;
         $result = this.place_order (usrName, friedChickenQuant, colaQuant);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // OrderApp/Order/check_order_status
       {
         String usrName = in.read_string ();
         String $result = null;
         $result = this.check_order_status (usrName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // OrderApp/Order/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:OrderApp/Order:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Order _this() 
  {
    return OrderHelper.narrow(
    super._this_object());
  }

  public Order _this(org.omg.CORBA.ORB orb) 
  {
    return OrderHelper.narrow(
    super._this_object(orb));
  }


} // class OrderPOA
