package OrderApp;

/**
* OrderApp/OrderHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Order.idl
* Friday, March 17, 2023 2:29:59 PM CDT
*/

public final class OrderHolder implements org.omg.CORBA.portable.Streamable
{
  public OrderApp.Order value = null;

  public OrderHolder ()
  {
  }

  public OrderHolder (OrderApp.Order initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = OrderApp.OrderHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    OrderApp.OrderHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return OrderApp.OrderHelper.type ();
  }

}
