package OrderApp;


/**
* OrderApp/OrderOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Order.idl
* Thursday, March 16, 2023 1:18:07 AM CDT
*/

public interface OrderOperations 
{
  String view_menu ();
  String place_order (String usrName, short friedChickenQuant, short colaQuant);
  String check_order_status (String usrName);
  String view_current_orders ();
  void shutdown ();
} // interface OrderOperations
