package OrderApp;


/**
* OrderApp/Order.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Order.idl
* Friday, March 17, 2023 2:04:39 PM CDT
*/

public interface Order extends OrderOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Order
