package OrderApp;


/**
* OrderApp/Order.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Order.idl
* Thursday, March 16, 2023 1:07:44 AM CDT
*/

public interface Order extends OrderOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Order
