package OrderApp;


/**
* OrderApp/OrderHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Order.idl
* Thursday, March 16, 2023 1:07:44 AM CDT
*/

abstract public class OrderHelper
{
  private static String  _id = "IDL:OrderApp/Order:1.0";

  public static void insert (org.omg.CORBA.Any a, OrderApp.Order that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static OrderApp.Order extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (OrderApp.OrderHelper.id (), "Order");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static OrderApp.Order read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_OrderStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, OrderApp.Order value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static OrderApp.Order narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof OrderApp.Order)
      return (OrderApp.Order)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      OrderApp._OrderStub stub = new OrderApp._OrderStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static OrderApp.Order unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof OrderApp.Order)
      return (OrderApp.Order)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      OrderApp._OrderStub stub = new OrderApp._OrderStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
